### ISSUE TITLE
Error: [ng:areq] Argument 'ChatAppCtrl' is not a function, got undefined

### ISSUE THREAD

**Issue by khedup3696** [tpiros/AngularChat#3]
Hi Tamas
I really appreciate your tutorial about the chats using socket.io and angular. I tried to install your angularchat but it's giving error

Error: [ng:areq] Argument 'ChatAppCtrl' is not a function, got undefined

it's also not displaying the value of the variable on the web page.

what could have gone wrong, my be problem with my installation.

with regards

khedup

(https://cloud.githubusercontent.com/assets/6446494/7654832/3bdec972-fb63-11e4-9f24-230e31aa2a3b.png)

**Comment by khedup3696** [comment]
Sorry My mistake. it's all good, thank you for your good work, please keep your good effort

**Comment by tpiros** [comment]
no worries :)

**Comment by arsidnal16** [comment]
I am getting the same error how to resolve this?
