### ISSUE TITLE
issue with socket.on

### ISSUE THREAD

**Issue by arsidnal16** [tpiros/AngularChat#4]
Hi Tamas

I am having 2 issues.

One of them is the same old one

Error: [ng:areq] Argument 'ChatAppCtrl' is not a function, got undefined

it's also not displaying the value of the variable on the web page.

what could have gone wrong, my be problem with my installation.

2nd is if I make changes to changes to controller.js then this is showing in my console:

"TypeError: Cannot read property 'on' of undefined
    at new ChatAppCtrl (controllers.js:55)"

This error is on socket.on..

Thank you for your help.

Regards
Siddhartha
(bravosid@gmail.com)

(https://cloud.githubusercontent.com/assets/6446494/7654832/3bdec972-fb63-11e4-9f24-230e31aa2a3b.png)

**Comment by khedup3696** [comment]
hi 
you have it install like this

npm install && install bower

**Comment by arsidnal16** [comment]
Hi, 

That didnt work..

**Comment by khedup3696** [comment]
sorry it's 
npm install && bower install

**Comment by arsidnal16** [comment]
I have all the things installed.. socket,express , bower..this is not the issue

**Comment by khedup3696** [comment]
I had the same problem, when i install separately, but with above command it's install the right dependency version that the app required, if you install your way, it's installing the latest libraries, and you will end up with this error

**Comment by arsidnal16** [comment]
Dude I have done ALL OF THAT.. Do you think I will not try that? I have been stuck on this for 16 hours now.. So I have done 9000 permutations and combinations by now..I have tried every single way of installing all that so stop saying that already..

**Comment by tpiros** [comment]
@arsidnal16 I have cloned the repository, then installed all npm packages by running `npm install` followed by `bower install`. Starting up the application using `node app.js` worked just fine.

Make sure that the AngularJS version is 1.2.x (For this project I was using 1.2.28). Probably I should lock down the bower dependencies as well.

**Comment by arsidnal16** [comment]
What do I have to do to run angularjs 1.2.x?

**Comment by tpiros** [comment]
use bower to install it: `bower install angular#1.2.28`

**Comment by arsidnal16** [comment]
this command in my terminal leads to

"-bash: bower: command not found"

**Comment by arsidnal16** [comment]
when i download your package and reach it from my terminal and then execute "npm install"

It says 

"npm WARN prefer global bower@1.2.8 should be installed with -g
npm WARN prefer global nodemon@1.0.13 should be installed with -g"

**Comment by tpiros** [comment]
install bower then - `npm install bower@1.2.8 -g` which will install the bower package globally (albeight an older version).

These are the basics of bower/npm and have nothing to do with my project - please read up on this topic

**Comment by arsidnal16** [comment]
I have one more question.. I installed these and run them so they run on the port 3000.. when I try to change the port to some other port like 3500 it doesnt work..

**Comment by tpiros** [comment]
https://github.com/tamaspiros/AngularChat#setup-and-configuration

**Comment by tpiros** [comment]
also make use to use a port that's available on your system and not being used by another application

**Comment by arsidnal16** [comment]
i executed everything and it installed everything with your instructions

i executed this finally 

Siddharthas-MBP:angularchat-master root# node app.js

it lead to this:

   info  - socket.io started
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server listening on IP/hostname: "192.168.1.4" and port: "3700"

But the page shows nothing..I changed the port number in app.js and services.js to 3700..

**Comment by arsidnal16** [comment]
![screen shot 2015-06-15 at 2 14 44 pm](https://cloud.githubusercontent.com/assets/12207421/8156240/f740d260-1368-11e5-9816-b713e20039bf.png)
This is what happened when I did it with port number 3000..

**Comment by tpiros** [comment]
okay. so read the log message: "Express server listening on IP/hostname: "192.168.1.4" and port: "3700".

Then in your screenshot you are using "localhost:3000".

Try to use the same hostname/IP address & port number throughout the system and it'll work.

**Comment by arsidnal16** [comment]
those are 2 different scenarios..different problems..

**Comment by tpiros** [comment]
I'm not longer sure how further I can help. Closing this issue as it doesn't occur on the environments that I have run my tests.
